local path = import 'path'

local passed, failed = 0, 0
local function expect(fn, expected, ...)
    local result = fn(...)
    if result == expected then
        passed = passed + 1
    else
        failed = failed + 1
        print('expected \'' .. expected .. '\', got \'' .. tostring(result) .. '\' at ' .. tostring(...))
    end
end

expect(path.posix.isSeparator, true, '/')
expect(path.posix.isSeparator, false, '\\')
expect(path.posix.isSeparator, false, 'a')

expect(path.posix.isAbsolute, false, '')
expect(path.posix.isAbsolute, true, '/a')
expect(path.posix.isAbsolute, true, '/a/..')
expect(path.posix.isAbsolute, false, 'a/')
expect(path.posix.isAbsolute, false, './a')

expect(path.posix.dirname, '/a/b', '/a/b/c')
expect(path.posix.dirname, '/a/b', '/a/b/c///')
expect(path.posix.dirname, '/', '/a')
expect(path.posix.dirname, '', '/')
expect(path.posix.dirname, '', '//')
expect(path.posix.dirname, '', '///')
expect(path.posix.dirname, '', '////')
expect(path.posix.dirname, '', '')
expect(path.posix.dirname, '', 'a')
expect(path.posix.dirname, '', 'a/')
expect(path.posix.dirname, '', 'a//')

expect(path.posix.basename, '', '')
expect(path.posix.basename, '', '/')
expect(path.posix.basename, 'basename.ext', '/dir/basename.ext')
expect(path.posix.basename, 'basename.ext', '/basename.ext')
expect(path.posix.basename, 'basename.ext', 'basename.ext')
expect(path.posix.basename, 'basename.ext', 'basename.ext/')
expect(path.posix.basename, 'basename.ext', 'basename.ext//')
expect(path.posix.basename, '.basename', '.basename')

expect(path.posix.basename, 'basename', '/dir/basename.ext', true)
expect(path.posix.basename, 'basename', '/basename.ext', true)
expect(path.posix.basename, 'basename', 'basename.ext', true)
expect(path.posix.basename, 'basename', 'basename.ext/', true)
expect(path.posix.basename, 'basename', 'basename.ext//', true)
expect(path.posix.basename, 'basename', 'basename.ext//', true)
expect(path.posix.basename, 'basename.1', 'basename.1.ext', true)
expect(path.posix.basename, '.basename', '.basename', true)

expect(path.posix.basename, 'basename', '/dir/basename.ext', '.ext')
expect(path.posix.basename, 'basename', '/basename.ext', '.ext')
expect(path.posix.basename, 'basename', 'basename.ext', '.ext')
expect(path.posix.basename, 'basename', 'basename.ext/', '.ext')
expect(path.posix.basename, 'basename', 'basename.ext//', '.ext')
expect(path.posix.basename, 'basename.1', 'basename.1.ext', '.ext')
expect(path.posix.basename, 'bbb', '/aaa/bbb', '.ext')

expect(path.posix.basename, 'bbb', '/aaa/bbb')
expect(path.posix.basename, 'aaa', '/aaa/')
expect(path.posix.basename, 'b', '/aaa/b')
expect(path.posix.basename, 'b', '/a/b')
expect(path.posix.basename, 'a', '//a')
expect(path.posix.basename, '\\dir\\basename.ext', '\\dir\\basename.ext')
expect(path.posix.basename, '\\basename.ext', '\\basename.ext')
expect(path.posix.basename, 'basename.ext\\', 'basename.ext\\')

expect(path.posix.extension, '', '')
expect(path.posix.extension, '', '.')
expect(path.posix.extension, '.', 'a.')
expect(path.posix.extension, '.', 'abc.')
expect(path.posix.extension, '', '.a')
expect(path.posix.extension, '', '.file')
expect(path.posix.extension, '', '.gitignore')
expect(path.posix.extension, '.png', '.image.png')
expect(path.posix.extension, '.ext', 'file.ext')
expect(path.posix.extension, '.', 'file.ext.')
expect(path.posix.extension, '.bruh', 'very-long-file.bruh')
expect(path.posix.extension, '.c', 'a.b.c')
expect(path.posix.extension, '.c', 'a.b.c/')

expect(path.posix.extension, '', '/')
expect(path.posix.extension, '', '/.')
expect(path.posix.extension, '.', '/a.')
expect(path.posix.extension, '.', '/abc.')
expect(path.posix.extension, '', '/.a')
expect(path.posix.extension, '', '/.file')
expect(path.posix.extension, '', '/.gitignore')
expect(path.posix.extension, '.ext', '/file.ext')
expect(path.posix.extension, '.', '/file.ext.')
expect(path.posix.extension, '.bruh', '/very-long-file.bruh')
expect(path.posix.extension, '.c', '/a.b.c')
expect(path.posix.extension, '.c', '/a.b.c/')

expect(path.posix.extension, '', '/foo/bar/bam/')
expect(path.posix.extension, '', '/foo/bar/bam/.')
expect(path.posix.extension, '.', '/foo/bar/bam/a.')
expect(path.posix.extension, '.', '/foo/bar/bam/abc.')
expect(path.posix.extension, '', '/foo/bar/bam/.a')
expect(path.posix.extension, '', '/foo/bar/bam/.file')
expect(path.posix.extension, '', '/foo/bar/bam/.gitignore')
expect(path.posix.extension, '.ext', '/foo/bar/bam/file.ext')
expect(path.posix.extension, '.', '/foo/bar/bam/file.ext.')
expect(path.posix.extension, '.bruh', '/foo/bar/bam/very-long-file.bruh')
expect(path.posix.extension, '.c', '/foo/bar/bam/a.b.c')
expect(path.posix.extension, '.c', '/foo/bar/bam/a.b.c/')

expect(path.posix.getRoot, '.', '')
expect(path.posix.getRoot, '.', 'home')
expect(path.posix.getRoot, '.', '../home')
expect(path.posix.getRoot, '/', '/')
expect(path.posix.getRoot, '/', '/home')

expect(path.posix.normalize, '/', '/')
expect(path.posix.normalize, '/home', '/home')
expect(path.posix.normalize, '/home/..', '/home/..')
expect(path.posix.normalize, '/a/b/c', '/a/b/c')
expect(path.posix.normalize, '/a/b/c', '/a/b/c/')
expect(path.posix.normalize, '/', '/./')
expect(path.posix.normalize, '/../etc/../..', '/../etc/../..')
expect(path.posix.normalize, '/home', '/./home/.')
expect(path.posix.normalize, '/a/b/c', '/a/b/c/.')

expect(path.posix.normalize, 'home', 'home')
expect(path.posix.normalize, 'home/..', 'home/..')
expect(path.posix.normalize, 'a/b/c', 'a/b/c')
expect(path.posix.normalize, 'home', './home/.')
expect(path.posix.normalize, '../etc/../..', '../etc/../..')
expect(path.posix.normalize, 'a/b/c', 'a/b/c/.')

expect(path.posix.join, '')
expect(path.posix.join, '', '', '')
expect(path.posix.join, '/a/b/c', '/a/b', 'c')
expect(path.posix.join, '/a/b/c', '/a/b/', 'c')
expect(path.posix.join, '/a/b/c', '/', 'a', 'b/', 'c')
expect(path.posix.join, '/a/b/c', '/a/', 'b/', 'c')
expect(path.posix.join, '/a/b/c', '', '/', 'a', '', 'b/', 'c', '')
expect(path.posix.join, '/a/b/c', '/a/', '', '', 'b/', 'c')
expect(path.posix.join, '/b/c', 'a', '/b', 'c')
expect(path.posix.join, '/b/c', 'a/', '/b/', 'c')

print(module.file, 'passed:', passed, 'failed:', failed)
